# Generated by Django 4.1 on 2022-08-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["updated", "created"]},
        ),
    ]
